<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-1I1N647" failures="2" tests="4" name="Test(failed)" time="0.259" errors="0" timestamp="2022-02-10T13:36:54 IST">
  <testcase classname="javaPackage.TestNG2" name="assertionCheck" time="0.034">
    <failure type="java.lang.AssertionError" message="expected [Log in] but found [Lag in]">
      <![CDATA[java.lang.AssertionError: expected [Log in] but found [Lag in]
at javaPackage.TestNG2.assertionCheck(TestNG2.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- assertionCheck -->
  <testcase classname="javaPackage.TestNG6" name="e" time="0.006">
    <skipped/>
  </testcase> <!-- e -->
  <testcase classname="javaPackage.TestNG8" name="z" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at javaPackage.TestNG8.z(TestNG8.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- z -->
  <testcase classname="javaPackage.TestNG8" name="b" time="0.0">
    <skipped/>
  </testcase> <!-- b -->
  <testcase classname="javaPackage.TestNG6" name="d" time="0.0">
    <ignored/>
  </testcase> <!-- d -->
  <testcase classname="javaPackage.TestNG6" name="c" time="0.0">
    <ignored/>
  </testcase> <!-- c -->
  <testcase classname="javaPackage.TestNG6" name="b" time="0.0">
    <ignored/>
  </testcase> <!-- b -->
  <testcase classname="javaPackage.TestNG6" name="a" time="0.0">
    <ignored/>
  </testcase> <!-- a -->
</testsuite> <!-- Test(failed) -->
